export const exampleCategories = [
    { title: 'Plant', key: 'plant' },
    { title: 'Indoor Plant', key: 'indoor-plant' },
    { title: 'Outdoor Plant', key: 'outdoor-plant' },
    { title: 'Garden Tools', key: 'garden-tools' },
    { title: 'Ground Covers', key: 'ground-covers' },
    { title: 'Pots', key: 'pots' },
    { title: 'Mud Pots', key: 'mud-pots' },
    { title: 'Peshwari Pots', key: 'peshwari-pots' },
    { title: 'Gujarati Pots', key: 'gujarati-pots' },
    { title: 'Fancy Pots', key: 'fancy-pots' },
    { title: 'Ceramic Pots', key: 'ceramic-pots' },
    { title: 'Steal Pots', key: 'steal-pots' },
    { title: 'Plastic Pots', key: 'plastic-pots' },
    { title: 'Grow bag', key: 'grow-bag' },
    { title: 'Antique Pots', key: 'antique-pots' },
    { title: 'Seeds', key: 'seeds' },
    { title: 'Flower Seeds', key: 'flower-seeds' },
    { title: 'Vegetable Seeds', key: 'vegetable-seeds' },
    { title: 'Fruit Seeds', key: 'fruit-seeds' },
    { title: 'Palm Seeds', key: 'palm-seeds' },
    { title: 'Grass Seeds', key: 'grass-seeds' },
    { title: 'Gifts', key: 'gifts' },
    { title: 'Artificial Flower', key: 'artificial-flower' },
    { title: 'Bouquet', key: 'bouquet' },
    { title: 'Gajray', key: 'gajray' },
    { title: 'Original Plant', key: 'original-plant' },
    { title: 'Tools', key: 'tools' },
    { title: 'Fertilizers', key: 'fertilizers' },
    { title: 'Organic Fertilizers', key: 'organic-fertilizers' },
    { title: 'Seed Starter', key: 'seed-starter' },
    { title: 'Micro Nutrients', key: 'micro-nutrients' },
    { title: 'Rooting Harmons', key: 'rooting-harmons' },
    { title: 'Pesticides', key: 'pesticides' },
    { title: 'Fungicides', key: 'fungicides' },
    { title: 'Garden Fertilizer', key: 'garden-fertilizer' },
    { title: 'Services', key: 'services' },
    { title: 'Plantation ', key: 'plantation' },
    { title: 'Landscaping', key: 'landscaping' },
    { title: 'Interior Decoration', key: 'interior-decoration' },
    { title: 'Mali', key: 'mali' },
    { title: 'Lawn Restoration', key: 'lawn-restoration' },
    { title: 'Irrigation', key: 'irrigation' },
    { title: 'Trees', key: 'trees' },
    { title: 'Fruit Tree', key: 'fruit-tree' },
    { title: 'Citrus Fruit', key: 'citrus-fruit' },
    { title: 'Dates ', key: 'dates' },
    { title: 'Palm Tree', key: 'palm-tree' },
    { title: 'Table Plant', key: 'table-plant' },
    { title: 'Flower', key: 'flower' },
    { title: 'Bonsai Plants', key: 'bonsai-plants' },
    { title: 'Medical Plant', key: 'medical-plant' },
    { title: 'Bali or Creeper', key: 'bali-or-creeper' },
    { title: 'Roses', key: 'roses' },
    { title: 'Soil', key: 'soil' },
    { title: 'Pertile', key: 'pertile' },
    { title: 'Organic Compost', key: 'organic-compost' },
    { title: 'Bhal + Matti', key: 'bhal-+-matti' },
];
